### ISSUE TITLE
Convert figures from svg to eps

### ISSUE THREAD

**Issue by jdblischak** [jdblischak/git-for-science#1]
svg images display on Authorea, but cannot be used when exporting to pdf.

**Comment by erdavenport** [comment]
I deleted the svg images and instead added eps images (I also made some edits to the figures). 

The images actually don't have the same colors after uploading them to Authoria as they do on my computer (The colors are really bright on Authoria and much more muted in the actual file). Also, Authoria is auto-adjusting the size of the figures. Figure 3 is actually larger than Figure 2. Probably not an issue at all since I'm sure we'll submit figures separately for actual print, but just an FYI I didn't make that very complicated figure that small...

**Comment by jdblischak** [comment]
Thanks, Emily. Authorea provides an option to resize the image. I made Figure 3 larger. Feel free to adjust them to your preference.
