### ISSUE TITLE
remove pdf output from repository

### ISSUE THREAD

**Issue by faroit** [jdblischak/git-for-science#62]
First: Great paper. I will recommend this to my students.

One thing that might be a bit inconsistent... In the paper it states:

> ...things not to version control are large data files that never change, binary files (including Word and Excel documents), and the output of your code.

it would there be more consistent to remove the generated pdf output from the repository

**Comment by jdblischak** [comment]
Thanks for the feedback, @faroit. I'm glad you enjoyed the paper, and we look forward to receiving Pull Requests from your students.

> it would there be more consistent to remove the generated pdf output from the repository

Yes, you are correct that in general it is best to avoid version controlling binary files, especially those generated by your code. However, while it is important to stress to novice Git users the big difference in how Git handles plain-text versus binary files and to avoid drastically growing the size of the repo by committing code-generated files, we do not wish to be dogmatic about this. There are many reasons why one may decide this tradeoff is worth it, especially with the availability of Git hosting sites like GitHub, Bitbucket, etc. In this particular example, I included the PDF output directly in the repo so that any interested reader that finds this repository could easily view the PDF. Asking a reader to first install LaTeX is a big requirement if all they want to do is view the finished product. Yes, I could do something else like host the file publicly on Dropbox or my own web server, but simply including it in this repo accomplishes the same thing and also ensures that the PDF is always up-to-date.

**Comment by faroit** [comment]
why not use travis to build the document from source an [upload it as a github release](https://docs.travis-ci.com/user/build-stages/deploy-github-releases/) or even manual upload a github release?
